dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - aave/protocol-v2@1.0.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - Uniswap/v3-periphery@1.3.0
compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
      - "@uniswap-periphery=Uniswap/v3-periphery@1.3.0"
networks:
  kovan:
    weth_address: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    usdt_address: "0x13512979ade267ab5100878e2e0f485b568328a4"
    swap_router_address: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
  mainnet-fork:
    weth_address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    usdt_address: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    swap_router_address: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
  ftm-main-fork:
    ftm_address: ""
    mim_address: ""
    verify: False
  ftm-test:
    ftm_address: ""
    mim_address: ""
    verify: False
