dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # - geist-finance/geist-protocol@1.0.0
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - Uniswap/v3-periphery@1.3.0
compiler:
  solc:
    version: 0.8.11
    remappings:
      # - "@geist-finance=geist-finance/geist-protocol@1.0.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
      - "@uniswap-periphery=Uniswap/v3-periphery@1.3.0"
networks:
  default: ftm-main-fork-2
  ftm-main-fork:
    ftm_address: ""
    mim_address: ""
    verify: False
  ftm-test:
    ftm_address: ""
    mim_address: ""
    verify: False
  development:
    verify: False
