dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - aave/protocol-v2@1.0.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - Uniswap/v3-periphery@1.3.0
compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
      - "@uniswap-periphery=Uniswap/v3-periphery@1.3.0"
    ignore:
      - "./contracts/test_scratch/*"
networks:
  default: ftm-test
  mainnet:
    weth_address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    # DAI
    usdt_address: "0x6b175474e89094c44da98b954eedeac495271d0f"
    lending_pool_addresses_provider_address: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    dex_addresses:
      uniswap:
        swap_router_V2_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        uniswap_factory_address: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
  kovan:
    weth_address: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    usdt_address: "0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa"
    lending_pool_addresses_provider_address: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
    dex_addresses:
      default_dex: "uniswap"
      uniswap:
        swap_router_V2_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        uniswap_factory_address: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
  mainnet-fork:
    weth_address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    # DAI
    usdt_address: "0x6b175474e89094c44da98b954eedeac495271d0f"
    lending_pool_addresses_provider_address: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    dex_addresses:
      default_dex: "uniswap"
      uniswap:
        swap_router_V2_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        uniswap_factory_address: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
  ftm-main:
    # this is actually wFTM, but we keep the name weth for simplicity of code
    weth_address: "0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83"
    # this is USDC
    usdt_address: "0x04068da6c83afcfa0e13ba15a6696662335d5b75"
    lending_pool_addresses_provider_address: "0x6c793c628Fe2b480c5e6FB7957dDa4b9291F9c9b"
    dex_addresses:
      default_dex: "spiritswap"
      spookyswap:
        swap_router_V2_address: "0xF491e7B69E4244ad4002BC14e878a34207E38c29"
        uniswap_factory_address: "0x152eE697f2E276fA89E96742e9bB9aB1F2E61bE3"
      spiritswap:
        swap_router_V2_address: "0x16327E3FbDaCA3bcF7E38F5Af2599D2DDc33aE52"
        uniswap_factory_address: "0xEF45d134b73241eDa7703fa787148D9C9F4950b0"
  ftm-test:
    # this is actually wFTM, but we keep the name weth for simplicity of code
    weth_address: "0xf1277d1Ed8AD466beddF92ef448A132661956621"
    # unclear what address to be used here
    usdt_address: "0x076877073D287Ee8c10878B190d7166367899fdA"
    lending_pool_addresses_provider_address: "0x6c793c628Fe2b480c5e6FB7957dDa4b9291F9c9b"
    dex_addresses:
      default_dex: "spiritswap"
      spookyswap:
        swap_router_V2_address: "0xcCAFCf876caB8f9542d6972f87B5D62e1182767d"
        uniswap_factory_address: "0x5D479c2a7FB79E12Ac4eBBAeDB0322B4d5F9Fd02"
      spiritswap:
        swap_router_V2_address: "0x16327E3FbDaCA3bcF7E38F5Af2599D2DDc33aE52"
        uniswap_factory_address: "0xEF45d134b73241eDa7703fa787148D9C9F4950b0"
  ftm-main-fork:
    weth_address: "0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83"
    usdt_address: "0x04068da6c83afcfa0e13ba15a6696662335d5b75" # fUSDT
    lending_pool_addresses_provider_address: "0x6c793c628Fe2b480c5e6FB7957dDa4b9291F9c9b"
    dex_addresses:
      default_dex: "spiritswap"
      spookyswap:
        swap_router_V2_address: "0xF491e7B69E4244ad4002BC14e878a34207E38c29"
        uniswap_factory_address: "0x152eE697f2E276fA89E96742e9bB9aB1F2E61bE3"
      spiritswap:
        swap_router_V2_address: "0x16327E3FbDaCA3bcF7E38F5Af2599D2DDc33aE52"
        uniswap_factory_address: "0xEF45d134b73241eDa7703fa787148D9C9F4950b0"
